set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

set -g @continuum-restore 'on'
set -g default-terminal "screen-256color"

unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1

set -g mouse on
set -g set-clipboard on
bind -T copy-mode    WheelUpPane   send -N2 -X scroll-up
bind -T copy-mode    WheelDownPane send -N2 -X scroll-down
bind -T copy-mode-vi WheelUpPane   send -N2 -X scroll-up
bind -T copy-mode-vi WheelDownPane send -N2 -X scroll-down

# Exit copy-mode manually with q or Esc.
bind -T copy-mode    MouseDragEnd1Pane send -X copy-pipe "wl-copy"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe "wl-copy"

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

run '~/.config/tmux/plugins/tpm/tpm'
