[opener]
  edit = [
    { run = 'nvim "$@"', desc = "Edit", block = true, for = "unix" },
  ]
  xdg = [
    { run = 'xdg-open "$@"', orphan = true, desc = "Open (system default)", for = "unix" },
  ]

[open]
  prepend_rules = [
    { url = "*.typ", use = "xdg" },
  ]
